#Merging summary data for falcon 100kb and 1Mb windows into a single file
rm -r /scratch/jw5478/FalconProject/Projects/RefGenome8/Synthesis/Summary_Full/
mkdir /scratch/jw5478/FalconProject/Projects/RefGenome8/Synthesis/Summary_Full/
echo -e "Genome\tWindow\tREF_SCAFFOLD\tWinNum\tA\tC\tG\tT\tCpG\ttGC\ttBASES\tpGC\tuDelSV\tuInsSV\tuInvSV\tuSeg_DelSV\tuSeg_InsSV\tBPuDelSV\tBPuInsSV\tBPuInvSV\tBPuSeg_DelSV\tBPuSeg_InsSV\trDNA\trLTR\trLINE\trSINE\trUnknown\tBPrDNA\tBPrLTR\tBPrLINE\tBPrSINE\tBPrUnknown\tGENES\tSCAFF_SIZE\tSIZE_CAT\tTHRUSH_CHROM_MATCH\tKAKAPO_CHROM_MATCH\tSERIEMA_CHROM_MATCH\tTHRUSH_CLASS_MATCH\tKAKAPO_CLASS_MATCH\tSERIEMA_CLASS_MATCH\tOVERALL_CLASS_MATCH\tCLASS_MATCH_NUMBER\tCONSENSUS_CLASS_MATCH\twCpG_AT\twCpG_AG\twCpG_AC\twCpG_TA\twCpG_TC\twCpG_TG\twCpG_CA\twCpG_CT\twCpG_CG\twCpG_GA\twCpG_GT\twCpG_GC\tNumDeletion\tNumInsertion\tDeletionBP\tInsertionBP\tnCpG_AT\tnCpG_AG\tnCpG_AC\tnCpG_TA\tnCpG_TC\tnCpG_TG\tnCpG_CA\tnCpG_CT\tnCpG_CG\tnCpG_GA\tnCpG_GT\tnCpG_GC\twCPG_CombinedAT\twCPG_CombinedGC\tnCpG_CombinedAT\tnCpG_CombinedGC\tFALCO_CLASS_MATCH\tFalcoCLASS_MATCH_NUMBER\tFalcoCONSENSUS_CLASS_MATCH\tConFalcoSex_Chrom_Type\tROH" > /scratch/jw5478/FalconProject/Projects/RefGenome8/Synthesis/Summary_Full/AllultChromAnnotated100KBWindowsSummary.txt
echo -e "Genome\tWindow\tREF_SCAFFOLD\tWinNum\tA\tC\tG\tT\tCpG\ttGC\ttBASES\tpGC\tuDelSV\tuInsSV\tuInvSV\tuSeg_DelSV\tuSeg_InsSV\tBPuDelSV\tBPuInsSV\tBPuInvSV\tBPuSeg_DelSV\tBPuSeg_InsSV\trDNA\trLTR\trLINE\trSINE\trUnknown\tBPrDNA\tBPrLTR\tBPrLINE\tBPrSINE\tBPrUnknown\tGENES\tSCAFF_SIZE\tSIZE_CAT\tTHRUSH_CHROM_MATCH\tKAKAPO_CHROM_MATCH\tSERIEMA_CHROM_MATCH\tTHRUSH_CLASS_MATCH\tKAKAPO_CLASS_MATCH\tSERIEMA_CLASS_MATCH\tOVERALL_CLASS_MATCH\tCLASS_MATCH_NUMBER\tCONSENSUS_CLASS_MATCH\twCpG_AT\twCpG_AG\twCpG_AC\twCpG_TA\twCpG_TC\twCpG_TG\twCpG_CA\twCpG_CT\twCpG_CG\twCpG_GA\twCpG_GT\twCpG_GC\tNumDeletion\tNumInsertion\tDeletionBP\tInsertionBP\tnCpG_AT\tnCpG_AG\tnCpG_AC\tnCpG_TA\tnCpG_TC\tnCpG_TG\tnCpG_CA\tnCpG_CT\tnCpG_CG\tnCpG_GA\tnCpG_GT\tnCpG_GC\twCPG_CombinedAT\twCPG_CombinedGC\tnCpG_CombinedAT\tnCpG_CombinedGC\tFALCO_CLASS_MATCH\tFalcoCLASS_MATCH_NUMBER\tFalcoCONSENSUS_CLASS_MATCH\tConFalcoSex_Chrom_Type\tROH" > /scratch/jw5478/FalconProject/Projects/RefGenome8/Synthesis/Summary_Full/AllultChromAnnotated1MBWindowsSummary.txt
for s in A B C D E F FpBSx77 Kestrel
do
awk 'NR!=1{print $0}' /scratch/jw5478/FalconProject/Projects/RefGenome8/Synthesis/Windows/Summary/"$s"_ultChromAnnotatedWindowsSummary.txt >> /scratch/jw5478/FalconProject/Projects/RefGenome8/Synthesis/Summary_Full/AllultChromAnnotated100KBWindowsSummary.txt
awk 'NR!=1{print $0}' /scratch/jw5478/FalconProject/Projects/RefGenome8/Synthesis/Megabases/Windows/Summary/"$s"_ultChromAnnotatedWindowsMBSummary.txt >> /scratch/jw5478/FalconProject/Projects/RefGenome8/Synthesis/Summary_Full/AllultChromAnnotated1MBWindowsSummary.txt
done
