#!/bin/bash
#SBATCH --time=168:00:00
#SBATCH --mem=118GB
#SBATCH -p serial
# Set number of nodes to run
#SBATCH --nodes=1
# Set number of tasks to run
#SBATCH --ntasks=28
# Set number of cores per task (default is 1)
#SBATCH --cpus-per-task=1
# Output and error files
#SBATCH -o job.%J.out

module purge
module load perl
module load gencore/1
module load gencore_variant_detection/1.0
module load gencore_annotation/1.0

rm -r /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch
mkdir /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch
mkdir /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs

function make_snv_vcf {
f=`echo $v | perl -pe 's#.*/##g' | perl -pe 's#vcf.gz##'`
zcat $v | grep "#" > /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/"$f"snv.vcf
zcat $v | grep -v "#" | grep "SNV" >> /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/"$f"snv.vcf
bgzip /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/"$f"snv.vcf
bcftools index /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/"$f"snv.vcf.gz
}
function make_deletion_vcf {
f=`echo $v | perl -pe 's#.*/##g' | perl -pe 's#vcf.gz##'`
zcat $v | grep "#" > /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/"$f"deletion.vcf
zcat $v | grep -v "#" | grep "DELETION" >> /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/"$f"deletion.vcf
bgzip /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/"$f"deletion.vcf
bcftools index /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/"$f"deletion.vcf.gz
}
function make_insertion_vcf {
f=`echo $v | perl -pe 's#.*/##g' | perl -pe 's#vcf.gz##'`
zcat $v | grep "#" > /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/"$f"insertion.vcf
zcat $v | grep -v "#" | grep "INSERTION" >> /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/"$f"insertion.vcf
bgzip /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/"$f"insertion.vcf
bcftools index /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/"$f"insertion.vcf.gz
}

for v in $(ls /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/VCFs/Diploid/*-v-Kestrel100KBhap.dip.norm.vcf.gz)
do
make_snv_vcf &
make_deletion_vcf &
make_insertion_vcf &
done
wait

#make large falcon
mkdir /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Large
bcftools isec --nfiles=7 -w 1 -c none -p /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Large/SNV /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/A-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/B-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/C-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/D-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/E-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/F-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/FpBSx77-v-Kestrel100KBhap.dip.norm.snv.vcf.gz &
bcftools isec --nfiles=7 -w 1 -c none -p /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Large/Deletion /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/A-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/B-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/C-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/D-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/E-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/F-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/FpBSx77-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz &
bcftools isec --nfiles=7 -w 1 -c none -p /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Large/Insertion /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/A-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/B-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/C-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/D-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/E-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/F-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/FpBSx77-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz &
wait
bgzip --threads 8 /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Large/SNV/0000.vcf &
bgzip --threads 8 /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Large/Deletion/0000.vcf &
bgzip --threads 8 /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Large/Insertion/0000.vcf &
wait
bcftools index /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Large/SNV/0000.vcf.gz &
bcftools index /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Large/Deletion/0000.vcf.gz &
bcftools index /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Large/Insertion/0000.vcf.gz &
wait

#make Kestrel
mkdir /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Kestrel
bcftools isec --nfiles=1 -w 1 -c none -p /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Kestrel/SNV/ /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/Kestrel-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/A-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/B-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/C-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/D-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/E-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/F-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/FpBSx77-v-Kestrel100KBhap.dip.norm.snv.vcf.gz &
bcftools isec --nfiles=1 -w 1 -c none -p /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Kestrel/Deletion /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/Kestrel-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/A-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/B-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/C-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/D-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/E-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/F-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/FpBSx77-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz &
bcftools isec --nfiles=1 -w 1 -c none -p /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Kestrel/Insertion /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/Kestrel-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/A-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/B-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/C-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/D-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/E-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/F-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/FpBSx77-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz &
wait
bgzip --threads 8 /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Kestrel/SNV/0000.vcf &
bgzip --threads 8 /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Kestrel/Deletion/0000.vcf &
bgzip --threads 8 /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Kestrel/Insertion/0000.vcf &
wait
bcftools index /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Kestrel/SNV/0000.vcf.gz &
bcftools index /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Kestrel/Deletion/0000.vcf.gz &
bcftools index /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Kestrel/Insertion/0000.vcf.gz &
wait

#make Hierofalco
mkdir /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Hierofalco
bcftools isec --nfiles=4 -w 1 -c none -p /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Hierofalco/SNV /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/A-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/D-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/E-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/F-v-Kestrel100KBhap.dip.norm.snv.vcf.gz &
bcftools isec --nfiles=4 -w 1 -c none -p /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Hierofalco/Deletion /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/A-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/D-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/E-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/F-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz &
bcftools isec --nfiles=4 -w 1 -c none -p /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Hierofalco/Insertion /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/A-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/D-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/E-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/F-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz &
wait
bgzip --threads 8 /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Hierofalco/SNV/0000.vcf &
bgzip --threads 8 /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Hierofalco/Deletion/0000.vcf &
bgzip --threads 8 /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Hierofalco/Insertion/0000.vcf &
wait
bcftools index /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Hierofalco/SNV/0000.vcf.gz &
bcftools index /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Hierofalco/Deletion/0000.vcf.gz &
bcftools index /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Hierofalco/Insertion/0000.vcf.gz &
wait

#make Peregrine
mkdir /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Peregrine
bcftools isec --nfiles=3 -w 1 -c none -p /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Peregrine/SNV /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/B-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/C-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/FpBSx77-v-Kestrel100KBhap.dip.norm.snv.vcf.gz &
bcftools isec --nfiles=3 -w 1 -c none -p /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Peregrine/Deletion /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/B-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/C-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/FpBSx77-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz &
bcftools isec --nfiles=3 -w 1 -c none -p /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Peregrine/Insertion /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/B-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/C-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/FpBSx77-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz &
wait
bgzip --threads 8 /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Peregrine/SNV/0000.vcf &
bgzip --threads 8 /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Peregrine/Deletion/0000.vcf &
bgzip --threads 8 /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Peregrine/Insertion/0000.vcf &
wait
bcftools index /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Peregrine/SNV/0000.vcf.gz &
bcftools index /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Peregrine/Deletion/0000.vcf.gz &
bcftools index /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Peregrine/Insertion/0000.vcf.gz &
wait

#make Saker-Gyr
mkdir /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Saker-Gyr
bcftools isec --nfiles=3 -w 1 -c none -p /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Saker-Gyr/SNV /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/D-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/E-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/F-v-Kestrel100KBhap.dip.norm.snv.vcf.gz &
bcftools isec --nfiles=3 -w 1 -c none -p /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Saker-Gyr/Deletion /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/D-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/E-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/F-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz &
bcftools isec --nfiles=3 -w 1 -c none -p /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Saker-Gyr/Insertion /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/D-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/E-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/F-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz &
wait
bgzip --threads 8 /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Saker-Gyr/SNV/0000.vcf &
bgzip --threads 8 /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Saker-Gyr/Deletion/0000.vcf &
bgzip --threads 8 /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Saker-Gyr/Insertion/0000.vcf &
wait
bcftools index /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Saker-Gyr/SNV/0000.vcf.gz &
bcftools index /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Saker-Gyr/Deletion/0000.vcf.gz &
bcftools index /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Saker-Gyr/Insertion/0000.vcf.gz &
wait

#make just Gyrs
mkdir /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Gyr
bcftools isec --nfiles=2 -w 1 -c none -p /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Gyr/SNV /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/E-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/F-v-Kestrel100KBhap.dip.norm.snv.vcf.gz &
bcftools isec --nfiles=2 -w 1 -c none -p /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Gyr/Deletion /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/E-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/F-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz &
bcftools isec --nfiles=2 -w 1 -c none -p /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Gyr/Insertion /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/E-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/F-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz &
wait
bgzip --threads 8 /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Gyr/SNV/0000.vcf &
bgzip --threads 8 /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Gyr/Deletion/0000.vcf &
bgzip --threads 8 /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Gyr/Insertion/0000.vcf &
wait
bcftools index /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Gyr/SNV/0000.vcf.gz &
bcftools index /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Gyr/Deletion/0000.vcf.gz &
bcftools index /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Gyr/Insertion/0000.vcf.gz &
wait

#make Peregrine sub-species
mkdir /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/SubPeregrine
bcftools isec --nfiles=2 -w 1 -c none -p /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/SubPeregrine/SNV /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/B-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/FpBSx77-v-Kestrel100KBhap.dip.norm.snv.vcf.gz &
bcftools isec --nfiles=2 -w 1 -c none -p /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/SubPeregrine/Deletion /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/B-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/FpBSx77-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz &
bcftools isec --nfiles=2 -w 1 -c none -p /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/SubPeregrine/Insertion /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/B-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/FpBSx77-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz &
wait
bgzip --threads 8 /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/SubPeregrine/SNV/0000.vcf &
bgzip --threads 8 /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/SubPeregrine/Deletion/0000.vcf &
bgzip --threads 8 /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/SubPeregrine/Insertion/0000.vcf &
wait
bcftools index /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/SubPeregrine/SNV/0000.vcf.gz &
bcftools index /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/SubPeregrine/Deletion/0000.vcf.gz &
bcftools index /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/SubPeregrine/Insertion/0000.vcf.gz &
wait

#Only Unique Shared in Large
bcftools isec --nfiles=1 -w 1 -c none -p /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Large/SNV/strip /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Large/SNV/0000.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/Kestrel-v-Kestrel100KBhap.dip.norm.snv.vcf.gz  &
bcftools isec --nfiles=1 -w 1 -c none -p /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Large/Deletion/strip /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Large/Deletion/0000.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/Kestrel-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz &
bcftools isec --nfiles=1 -w 1 -c none -p /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Large/Insertion/strip /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Large/Insertion/0000.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/Kestrel-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz &

#Only Unique Shared in Kestrel
bcftools isec --nfiles=1 -w 1 -c none -p /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Kestrel/SNV/strip /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Kestrel/SNV/0000.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/A-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/B-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/C-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/D-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/E-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/F-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/FpBSx77-v-Kestrel100KBhap.dip.norm.snv.vcf.gz &
bcftools isec --nfiles=1 -w 1 -c none -p /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Kestrel/Deletion/strip /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Kestrel/Deletion/0000.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/A-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/B-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/C-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/D-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/E-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/F-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/FpBSx77-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz &
bcftools isec --nfiles=1 -w 1 -c none -p /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Kestrel/Insertion/strip /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Kestrel/Insertion/0000.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/A-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/B-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/C-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/D-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/E-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/F-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/FpBSx77-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz &

#Only Unique Shared in Hierofalco
bcftools isec --nfiles=1 -w 1 -c none -p /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Hierofalco/SNV/strip /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Hierofalco/SNV/0000.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/B-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/C-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/FpBSx77-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/Kestrel-v-Kestrel100KBhap.dip.norm.snv.vcf.gz &
bcftools isec --nfiles=1 -w 1 -c none -p /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Hierofalco/Deletion/strip /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Hierofalco/Deletion/0000.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/B-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/C-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/FpBSx77-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/Kestrel-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz &
bcftools isec --nfiles=1 -w 1 -c none -p /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Hierofalco/Insertion/strip /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Hierofalco/Insertion/0000.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/B-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/C-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/FpBSx77-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/Kestrel-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz &

#Only Unique Shared in Peregrine
bcftools isec --nfiles=1 -w 1 -c none -p /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Peregrine/SNV/strip /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Peregrine/SNV/0000.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/A-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/D-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/E-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/F-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/Kestrel-v-Kestrel100KBhap.dip.norm.snv.vcf.gz &
bcftools isec --nfiles=1 -w 1 -c none -p /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Peregrine/Deletion/strip /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Peregrine/Deletion/0000.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/A-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/D-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/E-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/F-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/Kestrel-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz &
bcftools isec --nfiles=1 -w 1 -c none -p /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Peregrine/Insertion/strip /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Peregrine/Insertion/0000.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/A-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/D-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/E-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/F-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/Kestrel-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz &

#Only Unique Shared in Saker-Gyr
bcftools isec --nfiles=1 -w 1 -c none -p /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Saker-Gyr/SNV/strip /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Saker-Gyr/SNV/0000.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/A-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/B-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/C-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/FpBSx77-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/Kestrel-v-Kestrel100KBhap.dip.norm.snv.vcf.gz &
bcftools isec --nfiles=1 -w 1 -c none -p /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Saker-Gyr/Deletion/strip /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Saker-Gyr/Deletion/0000.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/A-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/B-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/C-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/FpBSx77-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/Kestrel-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz &
bcftools isec --nfiles=1 -w 1 -c none -p /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Saker-Gyr/Insertion/strip /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Saker-Gyr/Insertion/0000.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/A-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/B-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/C-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/FpBSx77-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/Kestrel-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz &

#Only Unique Shared in Gyr
bcftools isec --nfiles=1 -w 1 -c none -p /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Gyr/SNV/strip /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Gyr/SNV/0000.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/A-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/B-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/C-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/D-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/FpBSx77-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/Kestrel-v-Kestrel100KBhap.dip.norm.snv.vcf.gz &
bcftools isec --nfiles=1 -w 1 -c none -p /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Gyr/Deletion/strip /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Gyr/Deletion/0000.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/A-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/B-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/C-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/D-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/FpBSx77-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/Kestrel-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz &
bcftools isec --nfiles=1 -w 1 -c none -p /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Gyr/Insertion/strip /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Gyr/Insertion/0000.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/A-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/B-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/C-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/D-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/FpBSx77-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/Kestrel-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz &

#Only Unique Shared in SubPeregrine
bcftools isec --nfiles=1 -w 1 -c none -p /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/SubPeregrine/SNV/strip /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/SubPeregrine/SNV/0000.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/A-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/C-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/D-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/E-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/F-v-Kestrel100KBhap.dip.norm.snv.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/Kestrel-v-Kestrel100KBhap.dip.norm.snv.vcf.gz &
bcftools isec --nfiles=1 -w 1 -c none -p /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/SubPeregrine/Deletion/strip /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/SubPeregrine/Deletion/0000.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/A-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/C-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/D-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/E-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/F-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/Kestrel-v-Kestrel100KBhap.dip.norm.deletion.vcf.gz &
bcftools isec --nfiles=1 -w 1 -c none -p /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/SubPeregrine/Insertion/strip /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/SubPeregrine/Insertion/0000.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/A-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/C-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/D-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/E-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/F-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/VCFs/Kestrel-v-Kestrel100KBhap.dip.norm.insertion.vcf.gz &
wait

for f in $(ls /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/*/*/strip/*.vcf)
do
bgzip $f &
done
wait

for f in $(ls /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/*/*/strip/*.vcf.gz)
do
bcftools index $f &
done
wait

echo -e "Clade\tShared_SNVs\tShared_Deletions\tShared_Insertions" > /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/CladeSharedSummary.txt

Large_SNV=`zcat /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Large/SNV/strip/0000.vcf.gz | grep -v "#" | uniq | wc | awk '{print $1}'`
Large_Deletions=`zcat /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Large/Deletion/strip/0000.vcf.gz | grep -v "#" | uniq | wc | awk '{print $1}'`
Large_Insertions=`zcat /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Large/Insertion/strip/0000.vcf.gz | grep -v "#" | uniq | wc | awk '{print $1}'`
echo -e "Large\t$Large_SNV\t$Large_Deletions\t$Large_Insertions" >> /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/CladeSharedSummary.txt

Kestrel_SNV=`zcat /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Kestrel/SNV/strip/0000.vcf.gz | grep -v "#" | uniq | wc | awk '{print $1}'`
Kestrel_Deletions=`zcat /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Kestrel/Deletion/strip/0000.vcf.gz | grep -v "#" | uniq | wc | awk '{print $1}'`
Kestrel_Insertions=`zcat /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Kestrel/Insertion/strip/0000.vcf.gz | grep -v "#" | uniq | wc | awk '{print $1}'`

fullKestrel_SNV=`expr $Kestrel_SNV + $Large_SNV`
fullKestrel_Deletions=`expr $Kestrel_Deletions + $Large_Insertions`
fullKestrel_Insertions=`expr $Kestrel_Insertions + $Large_Deletions`
echo -e "Kestrel\t$fullKestrel_SNV\t$fullKestrel_Deletions\t$fullKestrel_Insertions" >> /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/CladeSharedSummary.txt

Hierofalco_SNV=`zcat /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Hierofalco/SNV/strip/0000.vcf.gz | grep -v "#" | uniq | wc | awk '{print $1}'`
Hierofalco_Deletions=`zcat /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Hierofalco/Deletion/strip/0000.vcf.gz | grep -v "#" | uniq | wc | awk '{print $1}'`
Hierofalco_Insertions=`zcat /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Hierofalco/Insertion/strip/0000.vcf.gz | grep -v "#" | uniq | wc | awk '{print $1}'`
echo -e "Hierofalco\t$Hierofalco_SNV\t$Hierofalco_Deletions\t$Hierofalco_Insertions" >> /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/CladeSharedSummary.txt

Peregrine_SNV=`zcat /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Peregrine/SNV/strip/0000.vcf.gz | grep -v "#" | uniq | wc | awk '{print $1}'`
Peregrine_Deletions=`zcat /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Peregrine/Deletion/strip/0000.vcf.gz | grep -v "#" | uniq | wc | awk '{print $1}'`
Peregrine_Insertions=`zcat /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Peregrine/Insertion/strip/0000.vcf.gz | grep -v "#" | uniq | wc | awk '{print $1}'`
echo -e "Peregrine\t$Peregrine_SNV\t$Peregrine_Deletions\t$Peregrine_Insertions" >> /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/CladeSharedSummary.txt

Saker_Gyr_SNV=`zcat /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Saker-Gyr/SNV/strip/0000.vcf.gz | grep -v "#" | uniq | wc | awk '{print $1}'`
Saker_Gyr_Deletions=`zcat /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Saker-Gyr/Deletion/strip/0000.vcf.gz | grep -v "#" | uniq | wc | awk '{print $1}'`
Saker_Gyr_Insertions=`zcat /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Saker-Gyr/Insertion/strip/0000.vcf.gz | grep -v "#" | uniq | wc | awk '{print $1}'`
echo -e "Saker-Gyr\t$Saker_Gyr_SNV\t$Saker_Gyr_Deletions\t$Saker_Gyr_Insertions" >> /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/CladeSharedSummary.txt

Gyr_SNV=`zcat /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Gyr/SNV/strip/0000.vcf.gz | grep -v "#" | uniq | wc | awk '{print $1}'`
Gyr_Deletions=`zcat /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Gyr/Deletion/strip/0000.vcf.gz | grep -v "#" | uniq | wc | awk '{print $1}'`
Gyr_Insertions=`zcat /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/Gyr/Insertion/strip/0000.vcf.gz | grep -v "#" | uniq | wc | awk '{print $1}'`
echo -e "Gyr\t$Gyr_SNV\t$Gyr_Deletions\t$Gyr_Insertions" >> /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/CladeSharedSummary.txt

SubPeregrine_SNV=`zcat /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/SubPeregrine/SNV/strip/0000.vcf.gz | grep -v "#" | uniq | wc | awk '{print $1}'`
SubPeregrine_Deletions=`zcat /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/SubPeregrine/Deletion/strip/0000.vcf.gz | grep -v "#" | uniq | wc | awk '{print $1}'`
SubPeregrine_Insertions=`zcat /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/SubPeregrine/Insertion/strip/0000.vcf.gz | grep -v "#" | uniq | wc | awk '{print $1}'`
echo -e "SubPeregrine\t$SubPeregrine_SNV\t$SubPeregrine_Deletions\t$SubPeregrine_Insertions" >> /scratch/jw5478/FalconProject/Projects/RefGenome8/NucVar/Comparative/Kestrel_Alignments/SharedVariation/SharedSNV-INDELs/Branch/CladeSharedSummary.txt
